###########################################################
#
# This role can be called anytime to repeat creds download
#
#

- name: Get the credentials ZIP file
  shell: rm -rfv "{{ euca_admin_zip_file }}" ; euca-get-credentials {{ euca_admin_zip_file }}
  tags:
  - credentials
  - configure

- name: Creates the creds target directory
  shell: mkdir -p "{{ euca_admin_creds_path }}"
  tags:
  - credentials
  - configure
  ignore_errors: yes

- name: Unzip the credentials
  unarchive: copy=no src="{{ euca_admin_zip_file }}" dest="{{ euca_admin_creds_path }}" creates=yes
  tags:
  - credentials
  - configure

- name: Check services
  shell: source "{{ euca_admin_creds_path }}"/eucarc ; euca-describe-services
  tags:
  - credentials
  - debug
  - configure
  ignore_errors: yes
